name: Deploy to web app

on:
  release:
    types: [created]

jobs:
  run-on-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Display release info
        run: |
          echo "🎉 New Release Created!"
          echo "Release Tag: ${{ github.event.release.tag_name }}"
          echo "Release Name: ${{ github.event.release.name }}"
          echo "Release URL: ${{ github.event.release.html_url }}"
