name: Create Tag and Release on Merge

on:
  push:
    branches:
      - main

jobs:
  tag-and-release:
    name: Tag and Release
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch all tags
        run: git fetch --tags

      - name: Get latest tag
        id: get_tag
        run: |
          latest_tag=$(git tag --sort=-v:refname | head -n 1)
          if [[ -z "$latest_tag" ]]; then
            latest_tag="v0.0.0"
          fi
          echo "Latest tag: $latest_tag"
          echo "tag=$latest_tag" >> $GITHUB_OUTPUT

      - name: Bump patch version
        id: bump_version
        run: |
          old_tag="${{ steps.get_tag.outputs.tag }}"
          version="${old_tag#v}"
          IFS='.' read -r major minor patch <<< "$version"
          new_tag="v$major.$minor.$((patch + 1))"
          echo "New tag: $new_tag"
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT

      - name: Create new git tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ steps.bump_version.outputs.new_tag }}
          git push origin ${{ steps.bump_version.outputs.new_tag }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.bump_version.outputs.new_tag }}
          name: Release ${{ steps.bump_version.outputs.new_tag }}
          body: |
            🚀 Automatically created after PR merge to `main`.
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
